### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by jvanvorst** [a-akram-98/face_lib#3]
This might be a noob python question, but:

git clone https://github.com/a-akram-98/face_lib.git
cd face_lib/
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install face-library
...

(venv) jim@Jim-i9-Win10:src (master)$ python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from face_lib import face_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jim/source/face_lib/src/face_lib/__init__.py", line 1, in <module>
    from .face_lib import face_lib
  File "/home/jim/source/face_lib/src/face_lib/face_lib.py", line 5, in <module>
    from .BlazeDetector import BlazeFaceDetector
  File "/home/jim/source/face_lib/src/face_lib/BlazeDetector.py", line 5, in <module>
    from blazeFaceUtils import gen_anchors, AnchorsOptions
ModuleNotFoundError: No module named 'blazeFaceUtils'
>>> 

How do I find the modules?

**Comment by a-akram-98** [comment]
I have modified the repo and releases patch 1.1.3, please update the package
`pip install face-library -U`

**Comment by a-akram-98** [comment]
I will close the issue due to inactivity. If the problem wasn't solved, you can reopen the issue.
